[project]
name = "webots_py"
version = "0.1.1"
requires-python = ">=3.8"
dependencies = ["opencv-python"]

[tool.uv]
package = true # force building the package!

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["python"]
